#!/bin/bash

log() {
  echo "$*" 1>&2
}

fatal() {
  echo "$*" 1>&2
  exit 1
}

[ ! -e /run/log/pairdrop ] && mkfifo /run/log/pairdrop

cd /srv/pairdrop || fatal "Could not enter /srv/pairdrop"

if [ "${WS_FALLBACK}" = "true" ]; then
  exec node index.js --include-ws-fallback > /run/log/pairdrop 2>&1
else
  exec node index.js  > /run/log/pairdrop 2>&1
fi


